//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.296 版自动生成。
// 
#pragma warning disable 1591

namespace com.Utility.Webservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback g_SubmitOperationCompleted;
        
        private System.Threading.SendOrPostCallback g_SubmitWithKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback g_SchedulerSubmitOperationCompleted;
        
        private System.Threading.SendOrPostCallback g_SchedulerSubmitWithKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback VersionInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Sm_GetRemainOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangePasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback SingleInfoQueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback MsgPackageQueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback MsgSplitCalculateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::com.Utility.Properties.Settings.Default.com_Utility_Webservice_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event g_SubmitCompletedEventHandler g_SubmitCompleted;
        
        /// <remarks/>
        public event g_SubmitWithKeyCompletedEventHandler g_SubmitWithKeyCompleted;
        
        /// <remarks/>
        public event g_SchedulerSubmitCompletedEventHandler g_SchedulerSubmitCompleted;
        
        /// <remarks/>
        public event g_SchedulerSubmitWithKeyCompletedEventHandler g_SchedulerSubmitWithKeyCompleted;
        
        /// <remarks/>
        public event VersionInfoCompletedEventHandler VersionInfoCompleted;
        
        /// <remarks/>
        public event Sm_GetRemainCompletedEventHandler Sm_GetRemainCompleted;
        
        /// <remarks/>
        public event ChangePasswordCompletedEventHandler ChangePasswordCompleted;
        
        /// <remarks/>
        public event SingleInfoQueryCompletedEventHandler SingleInfoQueryCompleted;
        
        /// <remarks/>
        public event MsgPackageQueryCompletedEventHandler MsgPackageQueryCompleted;
        
        /// <remarks/>
        public event MsgSplitCalculateCompletedEventHandler MsgSplitCalculateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/g_Submit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CSubmitState g_Submit(string sname, string spwd, string scorpid, string sprdid, string sdst, string smsg) {
            object[] results = this.Invoke("g_Submit", new object[] {
                        sname,
                        spwd,
                        scorpid,
                        sprdid,
                        sdst,
                        smsg});
            return ((CSubmitState)(results[0]));
        }
        
        /// <remarks/>
        public void g_SubmitAsync(string sname, string spwd, string scorpid, string sprdid, string sdst, string smsg) {
            this.g_SubmitAsync(sname, spwd, scorpid, sprdid, sdst, smsg, null);
        }
        
        /// <remarks/>
        public void g_SubmitAsync(string sname, string spwd, string scorpid, string sprdid, string sdst, string smsg, object userState) {
            if ((this.g_SubmitOperationCompleted == null)) {
                this.g_SubmitOperationCompleted = new System.Threading.SendOrPostCallback(this.Ong_SubmitOperationCompleted);
            }
            this.InvokeAsync("g_Submit", new object[] {
                        sname,
                        spwd,
                        scorpid,
                        sprdid,
                        sdst,
                        smsg}, this.g_SubmitOperationCompleted, userState);
        }
        
        private void Ong_SubmitOperationCompleted(object arg) {
            if ((this.g_SubmitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.g_SubmitCompleted(this, new g_SubmitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/g_SubmitWithKey", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CSubmitState g_SubmitWithKey(string sname, string spwd, string scorpid, string sprdid, string sdst, string smsg, string key) {
            object[] results = this.Invoke("g_SubmitWithKey", new object[] {
                        sname,
                        spwd,
                        scorpid,
                        sprdid,
                        sdst,
                        smsg,
                        key});
            return ((CSubmitState)(results[0]));
        }
        
        /// <remarks/>
        public void g_SubmitWithKeyAsync(string sname, string spwd, string scorpid, string sprdid, string sdst, string smsg, string key) {
            this.g_SubmitWithKeyAsync(sname, spwd, scorpid, sprdid, sdst, smsg, key, null);
        }
        
        /// <remarks/>
        public void g_SubmitWithKeyAsync(string sname, string spwd, string scorpid, string sprdid, string sdst, string smsg, string key, object userState) {
            if ((this.g_SubmitWithKeyOperationCompleted == null)) {
                this.g_SubmitWithKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.Ong_SubmitWithKeyOperationCompleted);
            }
            this.InvokeAsync("g_SubmitWithKey", new object[] {
                        sname,
                        spwd,
                        scorpid,
                        sprdid,
                        sdst,
                        smsg,
                        key}, this.g_SubmitWithKeyOperationCompleted, userState);
        }
        
        private void Ong_SubmitWithKeyOperationCompleted(object arg) {
            if ((this.g_SubmitWithKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.g_SubmitWithKeyCompleted(this, new g_SubmitWithKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/g_SchedulerSubmit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CSubmitState g_SchedulerSubmit(string sname, string spwd, string scorpid, string sprdid, string sbegindate, string sdst, string smsg) {
            object[] results = this.Invoke("g_SchedulerSubmit", new object[] {
                        sname,
                        spwd,
                        scorpid,
                        sprdid,
                        sbegindate,
                        sdst,
                        smsg});
            return ((CSubmitState)(results[0]));
        }
        
        /// <remarks/>
        public void g_SchedulerSubmitAsync(string sname, string spwd, string scorpid, string sprdid, string sbegindate, string sdst, string smsg) {
            this.g_SchedulerSubmitAsync(sname, spwd, scorpid, sprdid, sbegindate, sdst, smsg, null);
        }
        
        /// <remarks/>
        public void g_SchedulerSubmitAsync(string sname, string spwd, string scorpid, string sprdid, string sbegindate, string sdst, string smsg, object userState) {
            if ((this.g_SchedulerSubmitOperationCompleted == null)) {
                this.g_SchedulerSubmitOperationCompleted = new System.Threading.SendOrPostCallback(this.Ong_SchedulerSubmitOperationCompleted);
            }
            this.InvokeAsync("g_SchedulerSubmit", new object[] {
                        sname,
                        spwd,
                        scorpid,
                        sprdid,
                        sbegindate,
                        sdst,
                        smsg}, this.g_SchedulerSubmitOperationCompleted, userState);
        }
        
        private void Ong_SchedulerSubmitOperationCompleted(object arg) {
            if ((this.g_SchedulerSubmitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.g_SchedulerSubmitCompleted(this, new g_SchedulerSubmitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/g_SchedulerSubmitWithKey", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CSubmitState g_SchedulerSubmitWithKey(string sname, string spwd, string scorpid, string sprdid, string sbegindate, string sdst, string smsg, string key) {
            object[] results = this.Invoke("g_SchedulerSubmitWithKey", new object[] {
                        sname,
                        spwd,
                        scorpid,
                        sprdid,
                        sbegindate,
                        sdst,
                        smsg,
                        key});
            return ((CSubmitState)(results[0]));
        }
        
        /// <remarks/>
        public void g_SchedulerSubmitWithKeyAsync(string sname, string spwd, string scorpid, string sprdid, string sbegindate, string sdst, string smsg, string key) {
            this.g_SchedulerSubmitWithKeyAsync(sname, spwd, scorpid, sprdid, sbegindate, sdst, smsg, key, null);
        }
        
        /// <remarks/>
        public void g_SchedulerSubmitWithKeyAsync(string sname, string spwd, string scorpid, string sprdid, string sbegindate, string sdst, string smsg, string key, object userState) {
            if ((this.g_SchedulerSubmitWithKeyOperationCompleted == null)) {
                this.g_SchedulerSubmitWithKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.Ong_SchedulerSubmitWithKeyOperationCompleted);
            }
            this.InvokeAsync("g_SchedulerSubmitWithKey", new object[] {
                        sname,
                        spwd,
                        scorpid,
                        sprdid,
                        sbegindate,
                        sdst,
                        smsg,
                        key}, this.g_SchedulerSubmitWithKeyOperationCompleted, userState);
        }
        
        private void Ong_SchedulerSubmitWithKeyOperationCompleted(object arg) {
            if ((this.g_SchedulerSubmitWithKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.g_SchedulerSubmitWithKeyCompleted(this, new g_SchedulerSubmitWithKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VersionInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VersionInfo() {
            object[] results = this.Invoke("VersionInfo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VersionInfoAsync() {
            this.VersionInfoAsync(null);
        }
        
        /// <remarks/>
        public void VersionInfoAsync(object userState) {
            if ((this.VersionInfoOperationCompleted == null)) {
                this.VersionInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVersionInfoOperationCompleted);
            }
            this.InvokeAsync("VersionInfo", new object[0], this.VersionInfoOperationCompleted, userState);
        }
        
        private void OnVersionInfoOperationCompleted(object arg) {
            if ((this.VersionInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VersionInfoCompleted(this, new VersionInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Sm_GetRemain", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CRemain Sm_GetRemain(string sname, string spwd, string scorpid, string sprdid) {
            object[] results = this.Invoke("Sm_GetRemain", new object[] {
                        sname,
                        spwd,
                        scorpid,
                        sprdid});
            return ((CRemain)(results[0]));
        }
        
        /// <remarks/>
        public void Sm_GetRemainAsync(string sname, string spwd, string scorpid, string sprdid) {
            this.Sm_GetRemainAsync(sname, spwd, scorpid, sprdid, null);
        }
        
        /// <remarks/>
        public void Sm_GetRemainAsync(string sname, string spwd, string scorpid, string sprdid, object userState) {
            if ((this.Sm_GetRemainOperationCompleted == null)) {
                this.Sm_GetRemainOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSm_GetRemainOperationCompleted);
            }
            this.InvokeAsync("Sm_GetRemain", new object[] {
                        sname,
                        spwd,
                        scorpid,
                        sprdid}, this.Sm_GetRemainOperationCompleted, userState);
        }
        
        private void OnSm_GetRemainOperationCompleted(object arg) {
            if ((this.Sm_GetRemainCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Sm_GetRemainCompleted(this, new Sm_GetRemainCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChangePassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ChangePassword(string account, string oldPassword, string newPassword) {
            object[] results = this.Invoke("ChangePassword", new object[] {
                        account,
                        oldPassword,
                        newPassword});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ChangePasswordAsync(string account, string oldPassword, string newPassword) {
            this.ChangePasswordAsync(account, oldPassword, newPassword, null);
        }
        
        /// <remarks/>
        public void ChangePasswordAsync(string account, string oldPassword, string newPassword, object userState) {
            if ((this.ChangePasswordOperationCompleted == null)) {
                this.ChangePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangePasswordOperationCompleted);
            }
            this.InvokeAsync("ChangePassword", new object[] {
                        account,
                        oldPassword,
                        newPassword}, this.ChangePasswordOperationCompleted, userState);
        }
        
        private void OnChangePasswordOperationCompleted(object arg) {
            if ((this.ChangePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangePasswordCompleted(this, new ChangePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SingleInfoQuery", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SigleMsgInfo SingleInfoQuery(string accountId, string accountPassWord, string productextendId, string mobilePhone, string msgcontent, string startTime, string endTime, string pageSize, string curPage, string MsgID) {
            object[] results = this.Invoke("SingleInfoQuery", new object[] {
                        accountId,
                        accountPassWord,
                        productextendId,
                        mobilePhone,
                        msgcontent,
                        startTime,
                        endTime,
                        pageSize,
                        curPage,
                        MsgID});
            return ((SigleMsgInfo)(results[0]));
        }
        
        /// <remarks/>
        public void SingleInfoQueryAsync(string accountId, string accountPassWord, string productextendId, string mobilePhone, string msgcontent, string startTime, string endTime, string pageSize, string curPage, string MsgID) {
            this.SingleInfoQueryAsync(accountId, accountPassWord, productextendId, mobilePhone, msgcontent, startTime, endTime, pageSize, curPage, MsgID, null);
        }
        
        /// <remarks/>
        public void SingleInfoQueryAsync(string accountId, string accountPassWord, string productextendId, string mobilePhone, string msgcontent, string startTime, string endTime, string pageSize, string curPage, string MsgID, object userState) {
            if ((this.SingleInfoQueryOperationCompleted == null)) {
                this.SingleInfoQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSingleInfoQueryOperationCompleted);
            }
            this.InvokeAsync("SingleInfoQuery", new object[] {
                        accountId,
                        accountPassWord,
                        productextendId,
                        mobilePhone,
                        msgcontent,
                        startTime,
                        endTime,
                        pageSize,
                        curPage,
                        MsgID}, this.SingleInfoQueryOperationCompleted, userState);
        }
        
        private void OnSingleInfoQueryOperationCompleted(object arg) {
            if ((this.SingleInfoQueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SingleInfoQueryCompleted(this, new SingleInfoQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MsgPackageQuery", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MsgPackageResult MsgPackageQuery(string accountid, string password, string msgid) {
            object[] results = this.Invoke("MsgPackageQuery", new object[] {
                        accountid,
                        password,
                        msgid});
            return ((MsgPackageResult)(results[0]));
        }
        
        /// <remarks/>
        public void MsgPackageQueryAsync(string accountid, string password, string msgid) {
            this.MsgPackageQueryAsync(accountid, password, msgid, null);
        }
        
        /// <remarks/>
        public void MsgPackageQueryAsync(string accountid, string password, string msgid, object userState) {
            if ((this.MsgPackageQueryOperationCompleted == null)) {
                this.MsgPackageQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMsgPackageQueryOperationCompleted);
            }
            this.InvokeAsync("MsgPackageQuery", new object[] {
                        accountid,
                        password,
                        msgid}, this.MsgPackageQueryOperationCompleted, userState);
        }
        
        private void OnMsgPackageQueryOperationCompleted(object arg) {
            if ((this.MsgPackageQueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MsgPackageQueryCompleted(this, new MsgPackageQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MsgSplitCalculate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MsgSplitCalculateResult MsgSplitCalculate(string accountId, string accountPassWord, string productextendId, uint mobilecount, string sms, uint mmslen) {
            object[] results = this.Invoke("MsgSplitCalculate", new object[] {
                        accountId,
                        accountPassWord,
                        productextendId,
                        mobilecount,
                        sms,
                        mmslen});
            return ((MsgSplitCalculateResult)(results[0]));
        }
        
        /// <remarks/>
        public void MsgSplitCalculateAsync(string accountId, string accountPassWord, string productextendId, uint mobilecount, string sms, uint mmslen) {
            this.MsgSplitCalculateAsync(accountId, accountPassWord, productextendId, mobilecount, sms, mmslen, null);
        }
        
        /// <remarks/>
        public void MsgSplitCalculateAsync(string accountId, string accountPassWord, string productextendId, uint mobilecount, string sms, uint mmslen, object userState) {
            if ((this.MsgSplitCalculateOperationCompleted == null)) {
                this.MsgSplitCalculateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMsgSplitCalculateOperationCompleted);
            }
            this.InvokeAsync("MsgSplitCalculate", new object[] {
                        accountId,
                        accountPassWord,
                        productextendId,
                        mobilecount,
                        sms,
                        mmslen}, this.MsgSplitCalculateOperationCompleted, userState);
        }
        
        private void OnMsgSplitCalculateOperationCompleted(object arg) {
            if ((this.MsgSplitCalculateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MsgSplitCalculateCompleted(this, new MsgSplitCalculateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CSubmitState {
        
        private int stateField;
        
        private string msgIDField;
        
        private string msgStateField;
        
        private int reserveField;
        
        /// <remarks/>
        public int State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string MsgID {
            get {
                return this.msgIDField;
            }
            set {
                this.msgIDField = value;
            }
        }
        
        /// <remarks/>
        public string MsgState {
            get {
                return this.msgStateField;
            }
            set {
                this.msgStateField = value;
            }
        }
        
        /// <remarks/>
        public int Reserve {
            get {
                return this.reserveField;
            }
            set {
                this.reserveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgSplitCalculateResult {
        
        private int resultCodeField;
        
        private string resultStateField;
        
        private uint pagesField;
        
        /// <remarks/>
        public int ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResultState {
            get {
                return this.resultStateField;
            }
            set {
                this.resultStateField = value;
            }
        }
        
        /// <remarks/>
        public uint Pages {
            get {
                return this.pagesField;
            }
            set {
                this.pagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgPackageSingleInfo {
        
        private int mobilePhonerQuantityField;
        
        private int chargeQuantityField;
        
        private int msgStateField;
        
        private int sendSuccessField;
        
        private int sendFailsField;
        
        private int sendFailTimesField;
        
        private int blackListsField;
        
        private int cancelsField;
        
        private int reportSuccessField;
        
        private int reportFailsField;
        
        /// <remarks/>
        public int MobilePhonerQuantity {
            get {
                return this.mobilePhonerQuantityField;
            }
            set {
                this.mobilePhonerQuantityField = value;
            }
        }
        
        /// <remarks/>
        public int ChargeQuantity {
            get {
                return this.chargeQuantityField;
            }
            set {
                this.chargeQuantityField = value;
            }
        }
        
        /// <remarks/>
        public int MsgState {
            get {
                return this.msgStateField;
            }
            set {
                this.msgStateField = value;
            }
        }
        
        /// <remarks/>
        public int SendSuccess {
            get {
                return this.sendSuccessField;
            }
            set {
                this.sendSuccessField = value;
            }
        }
        
        /// <remarks/>
        public int SendFails {
            get {
                return this.sendFailsField;
            }
            set {
                this.sendFailsField = value;
            }
        }
        
        /// <remarks/>
        public int SendFailTimes {
            get {
                return this.sendFailTimesField;
            }
            set {
                this.sendFailTimesField = value;
            }
        }
        
        /// <remarks/>
        public int BlackLists {
            get {
                return this.blackListsField;
            }
            set {
                this.blackListsField = value;
            }
        }
        
        /// <remarks/>
        public int Cancels {
            get {
                return this.cancelsField;
            }
            set {
                this.cancelsField = value;
            }
        }
        
        /// <remarks/>
        public int ReportSuccess {
            get {
                return this.reportSuccessField;
            }
            set {
                this.reportSuccessField = value;
            }
        }
        
        /// <remarks/>
        public int ReportFails {
            get {
                return this.reportFailsField;
            }
            set {
                this.reportFailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgPackageResult {
        
        private Error errorField;
        
        private MsgPackageSingleInfo[] resultField;
        
        /// <remarks/>
        public Error error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public MsgPackageSingleInfo[] result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Error {
        
        private string erroridField;
        
        private string errormsgField;
        
        /// <remarks/>
        public string errorid {
            get {
                return this.erroridField;
            }
            set {
                this.erroridField = value;
            }
        }
        
        /// <remarks/>
        public string errormsg {
            get {
                return this.errormsgField;
            }
            set {
                this.errormsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SingleResult {
        
        private string accountIdField;
        
        private string mobilePhoneField;
        
        private string msgContentField;
        
        private string productExtendIdField;
        
        private string resourceIdField;
        
        private string commitTimeField;
        
        private string sendStateField;
        
        private string reportStateField;
        
        private string departMentNameField;
        
        private string nameField;
        
        private string msgIDField;
        
        /// <remarks/>
        public string AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        public string MobilePhone {
            get {
                return this.mobilePhoneField;
            }
            set {
                this.mobilePhoneField = value;
            }
        }
        
        /// <remarks/>
        public string MsgContent {
            get {
                return this.msgContentField;
            }
            set {
                this.msgContentField = value;
            }
        }
        
        /// <remarks/>
        public string ProductExtendId {
            get {
                return this.productExtendIdField;
            }
            set {
                this.productExtendIdField = value;
            }
        }
        
        /// <remarks/>
        public string ResourceId {
            get {
                return this.resourceIdField;
            }
            set {
                this.resourceIdField = value;
            }
        }
        
        /// <remarks/>
        public string CommitTime {
            get {
                return this.commitTimeField;
            }
            set {
                this.commitTimeField = value;
            }
        }
        
        /// <remarks/>
        public string SendState {
            get {
                return this.sendStateField;
            }
            set {
                this.sendStateField = value;
            }
        }
        
        /// <remarks/>
        public string ReportState {
            get {
                return this.reportStateField;
            }
            set {
                this.reportStateField = value;
            }
        }
        
        /// <remarks/>
        public string DepartMentName {
            get {
                return this.departMentNameField;
            }
            set {
                this.departMentNameField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string MsgID {
            get {
                return this.msgIDField;
            }
            set {
                this.msgIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SigleMsgInfo {
        
        private Error errorField;
        
        private SingleResult[] resultField;
        
        private int totlenumField;
        
        /// <remarks/>
        public Error error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public SingleResult[] result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public int totlenum {
            get {
                return this.totlenumField;
            }
            set {
                this.totlenumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CRemain {
        
        private int stateField;
        
        private int remainField;
        
        /// <remarks/>
        public int State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public int Remain {
            get {
                return this.remainField;
            }
            set {
                this.remainField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void g_SubmitCompletedEventHandler(object sender, g_SubmitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class g_SubmitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal g_SubmitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CSubmitState Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CSubmitState)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void g_SubmitWithKeyCompletedEventHandler(object sender, g_SubmitWithKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class g_SubmitWithKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal g_SubmitWithKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CSubmitState Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CSubmitState)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void g_SchedulerSubmitCompletedEventHandler(object sender, g_SchedulerSubmitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class g_SchedulerSubmitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal g_SchedulerSubmitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CSubmitState Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CSubmitState)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void g_SchedulerSubmitWithKeyCompletedEventHandler(object sender, g_SchedulerSubmitWithKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class g_SchedulerSubmitWithKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal g_SchedulerSubmitWithKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CSubmitState Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CSubmitState)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void VersionInfoCompletedEventHandler(object sender, VersionInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VersionInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VersionInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Sm_GetRemainCompletedEventHandler(object sender, Sm_GetRemainCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Sm_GetRemainCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Sm_GetRemainCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CRemain Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CRemain)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ChangePasswordCompletedEventHandler(object sender, ChangePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SingleInfoQueryCompletedEventHandler(object sender, SingleInfoQueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SingleInfoQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SingleInfoQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SigleMsgInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SigleMsgInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void MsgPackageQueryCompletedEventHandler(object sender, MsgPackageQueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MsgPackageQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MsgPackageQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MsgPackageResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MsgPackageResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void MsgSplitCalculateCompletedEventHandler(object sender, MsgSplitCalculateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MsgSplitCalculateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MsgSplitCalculateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MsgSplitCalculateResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MsgSplitCalculateResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591